/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 SmrutiPankha_Model.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/SmrutiPankha_Model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Untitled.geometry} material={materials['Steel_-_Satin']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/SmrutiPankha_Model.gltf')
